apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData: #all the data comes from what i have in the .env file
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mydb
  MYSQL_USER: user
  MYSQL_PASSWORD: password
