services:
  #APPLICATION CONTAINERS NEEDED TO RUN THE APPLICATION
  mysql:
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mysql
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4000 #this value will change when i am un kubernetes
    volumes:
      - ./frontend:/app
    stdin_open: true #makes the frontend run in "interective mode"
    tty: true #makes the frontend run in "interective mode"

  #UTILITY CONTAINERS NEEDED TO CREATE AND/OR FILL THE APPLICATION FOLDERS
  npm-frontend:
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
  npm-backend:
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app

# at the same level as "services", here i should write all my named volumes
volumes:
  mysql_data:
